name: Increment Version

on:
  push:
    branches:
      -main
jobs:
  increment-version:
    runs-on:ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version:16

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: 
          git config user.name "Github Actions"
          git confing user.email "github-actions@github.com"

      - name: Check working status
        run:
          if ! git diff-index --quiet HEAD --; then 
            git stash
          fi

      - name: Increment version
        id: increment_version
        run: 
          NEW_VERSION=$(npm version patch -m "ðŸ–‹ï¸ Increase Version to %s")
          echo "NEW version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >>$GITHUB_ENV
          echo "name=NEW_VERSION=$NEW_VERSION" >>$GITHUB_OUTPUT

      - name; Push changes
        run:
          git push